trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: 5.0.x

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Sentinel/Sentinel.csproj'